---
title: "ghg"
author: "Joe Wertz"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
## Import libraries
library(tidyverse)
library(tidyr)
library(readr)
library(skimr)
library(dplyr)
library(ggplot2)
library(ggthemes)

```
# import the n2o data
# source:
```{r import_n2o}

n2o <- read_table("N2O_LawDome_MBL.txt", skip = 1, col_names = TRUE)
cols(
  year = col_date(),
  "N2O (ppb)" = col_double()
)
# rename column
n2o <- n2o %>% rename(n2o = "N2O (ppb)")

```

# create subset of n2o data from 1832-2018
```{r n2o_subset}
n2o_subset <- n2o %>% 
  filter(year >= 1832)
n2o_subset

```


# import the co2 data
# source: xxx
```{r import_co2}
co2 <- read_table("CO2_LawDome_MLO.txt", skip = 1, col_names = TRUE)
cols(
  year = col_date(),
  "CO2 (ppm)" = col_double()
)
# rename column
co2 <- co2 %>% rename(co2 = "CO2 (ppm)")

```

```{r n2o_subset_plot, echo=FALSE}
ggplot(data = n2o_subset, aes(x = year, y = n2o)) +
  geom_point() +
  labs(x = "Year", y = "n2o ppb") +
  ggtitle("N2O Emissions: 1832-2018")
  #scale_color_fivethirtyeight() +
  #theme_fivethirtyeight()

```

```{r co2_plot}
ggplot(data = co2, aes(x = year, y = co2)) + 
  geom_line()
```