---
title: "US Farm Data"
author: "Joe Wertz"
date: "11/22/2019"
output: html_document

### column definitions: https://quickstats.nass.usda.gov/api
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
## Import libraries
library(tidyverse)
library(tidyr)
library(readr)
library(skimr)
library(dplyr)
library(usdarnass)

```

```{r, set-key, include = FALSE}
# Set NASS key from .Renviron
readRenviron("C:/data/.Renviron")
Sys.getenv("NASS_KEY")
```
# get total us farms
```{r, us_total_farms}
us_total_farms <- nass_data(short_desc = "FARM OPERATIONS - NUMBER OF OPERATIONS",
                            source_desc = "CENSUS",
                            domain_desc = "TOTAL",
                            reference_period_desc = "YEAR",
                            agg_level_desc = "NATIONAL")
```
# get us farm size
```{r, us_farm_size}
us_farm_size <- nass_data(short_desc = "FARM OPERATIONS - ACRES OPERATED",
                            source_desc = "CENSUS",
                            domain_desc = "TOTAL",
                            reference_period_desc = "YEAR",
                            agg_level_desc = "NATIONAL")
```

# divide total acres by total farms to get average farm size
```{r, us_avg_farm}
us_avg_farm <- inner_join(us_total_farms, us_farm_size, by = "year")
us_avg_farm$Value.x = as.numeric(str_replace_all(us_avg_farm$Value.x, ",", ""))
us_avg_farm$Value.y = as.numeric(str_replace_all(us_avg_farm$Value.y, ",", ""))
# create new df by overwriting old df with new average_size column
us_avg_farm <- us_avg_farm %>% 
  mutate(average_size = Value.y/Value.x)
```
# get total corn acres planted at state level
```{r, state_corn_planted, include = FALSE}
corn_state <- nass_data(short_desc = "CORN - ACRES PLANTED",
                        reference_period_desc = "YEAR",
                        agg_level_desc = "STATE")
```
# get total corn acres planted at national level
```{r, us_corn_planted, include = FALSE}
us_corn <- nass_data(short_desc = "CORN - ACRES PLANTED",
                     reference_period_desc = "YEAR",
                     geo_level = "NATIONAL")
```
                     
# get total corn acres planted in corn belt states
```{r, corn_belt_planted, include = FALSE}
corn_belt <- corn_state %>% filter(state_name == "IOWA" |
                        state_name == "ILLINOIS" |
                        state_name == "INDIANA" |
                        state_name == "OHIO" |
                        state_name == "NEBRASKA" |
                        state_name == "KANSAS" |
                        state_name == "MINNESOTA" |
                        state_name == "MISSOURI" |
                        state_name == "SOUTH DAKOTA" |
                        state_name == "WISCONSIN")
```
# plot average_size of us farms
```{r}
ggplot(us_avg_farm, aes(x = year, 
                        y = average_size)) + 
  geom_point()
```


```{r}
ggplot(data = corn_belt,
       mapping = aes(x = Value,
                     y = year)) +
  geom_point()

```


